## Create an external secret lined to AWS Secrets Manager secret
## This will generate a kubernetes secret with the named "my-kubernetes-secret" in the demo namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: my-kubernetes-secret # Secret name in k8s
    creationPolicy: Owner

  ## You can get all of the secret content (recommended)
  dataFrom:
  - extract:
     key: prod/app/demo-secret

  ## Or you can get specific fields
  # data:
  # - secretKey: my-kubernetes-secret-field # Name of the field to store inside the k8s secret
  #   remoteRef:
  #     key: my-cloud-secret # Our AWS SecretsManager secret-name goes here
  #     property: password   # Retrieve the password field