apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-qa
  region: eu-central-1

vpc:
  subnets:
    public:
      eu-central-1a: { id: subnet-089da5e82f3b00561 }
      eu-central-1b: { id: subnet-05af31faca6b565f4 }
      eu-central-1c: { id: subnet-0c6a12ad6bf30ac5f }
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 30
    ssh:
      allow: false
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

iam:
  withOIDC: true
addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  resolveConflicts: overwrite